### ISSUE TITLE
Error when executing the script

### ISSUE THREAD

**Issue by MrAdam420** [similicious/berlin-buergeramt-bot#6]
node index.js
```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/home/pi/berlin-buergeramt-bot/node_modules/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by similicious** [comment]
Thanks! Fixed in https://github.com/similicious/berlin-buergeramt-bot/commit/c511fab3389d6536fadf680cef5dcc0a4ddfa803
